---
title: "Econometria 1 - Prática 3"
author: "Neylson Crepalde"
output:
  html_notebook: default
  pdf_document: default
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=F}
library(foreign)
library(magrittr)
library(normtest)

setwd('~/Documentos/Neylson Crepalde/Doutorado/Econometria1/aula_pratica2')

grandes = read.dta('Teste_normalidade_grandes_amostras.dta')
pequenas = read.dta('Teste_normalidade_pequenas_amostras.dta')
```

1) Gere 3 variáveis com distribuição normal e 3 variáveis com distribuição $\chi^2$:

```{r, message=FALSE, warning=FALSE}
#library(normtest)

x1 = rnorm(1084)
x2 = rnorm(1084)
x3 = rnorm(1084)

x12 = x1^2
x22 = x2^2
x32 = x3^2
```

c) Faça testes de normalidade nessas variáveis e nas variáveis de salário (salario e lsalario).

```{r testesnorm, message=FALSE, warning=FALSE}
# Jarque-Bera
sapply(list(x1,x2,x3,x12,x22,x32,grandes$salario, grandes$lsalario), jb.norm.test)

# Testes de Shapiro Wilk
sapply(list(x1,x2,x3,x12,x22,x32,grandes$salario, grandes$lsalario), shapiro.test)

qqnorm(x1)
qqnorm(grandes$salario)
qqnorm(grandes$lsalario)
qqnorm(x12)

qqnorm(pequenas$salario)
qqnorm(pequenas$lsalario)

```

